// <auto-generated />
using System;
using DBLayer.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DBLayer.Migrations
{
    [DbContext(typeof(PokedexContext))]
    partial class PokedexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DBLayer.Models.Pokemones", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IdRegion")
                        .HasColumnType("int");

                    b.Property<int>("IdTipos")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NavigationTipoPrimarioID")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Region")
                        .HasColumnType("int");

                    b.Property<int>("TipoPrimario")
                        .HasColumnType("int");

                    b.Property<int>("TipoSecundario")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("IdRegion");

                    b.HasIndex("IdTipos");

                    b.HasIndex("NavigationTipoPrimarioID");

                    b.ToTable("Pokemones");
                });

            modelBuilder.Entity("DBLayer.Models.Regiones", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Regiones");
                });

            modelBuilder.Entity("DBLayer.Models.Tipos", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Tipos");
                });

            modelBuilder.Entity("DBLayer.Models.Pokemones", b =>
                {
                    b.HasOne("DBLayer.Models.Regiones", "NavigationRegion")
                        .WithMany("RegionPokemones")
                        .HasForeignKey("IdRegion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBLayer.Models.Tipos", "NavigationTipoSecundario")
                        .WithMany("TiposPokemonesSecundarios")
                        .HasForeignKey("IdTipos")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DBLayer.Models.Tipos", "NavigationTipoPrimario")
                        .WithMany("TiposPokemones")
                        .HasForeignKey("NavigationTipoPrimarioID");

                    b.Navigation("NavigationRegion");

                    b.Navigation("NavigationTipoPrimario");

                    b.Navigation("NavigationTipoSecundario");
                });

            modelBuilder.Entity("DBLayer.Models.Regiones", b =>
                {
                    b.Navigation("RegionPokemones");
                });

            modelBuilder.Entity("DBLayer.Models.Tipos", b =>
                {
                    b.Navigation("TiposPokemones");

                    b.Navigation("TiposPokemonesSecundarios");
                });
#pragma warning restore 612, 618
        }
    }
}
